#!/usr/bin/python

from subprocess import *
import sys
import os
import restkit
import json
import re
from pprint import pprint

base_url = 'https://api.github.com/'
token = "token $GITHUB_OAUTH_TOKEN"

org = sys.argv[1]
repo = sys.argv[2]
pr = sys.argv[3]
comment = sys.argv[4]

# PR url
resource = restkit.Resource(base_url)
path = '/repos/%s/%s/issues/%s/comments' % (org, repo, pr)
print "Using path %s" % path
body = json.dumps({'body': comment})
response = resource.post(path, payload=body, headers={'Accept': 'application/json', 'Authorization': token})
json = json.loads(response.body_string())
print json

