#!/usr/bin/python

from subprocess import *
import sys
import os
import restkit
import json
import re
from pprint import pprint

base_url = 'https://api.github.com/'

org = sys.argv[1]
repo = sys.argv[2]
pr = sys.argv[3]

# PR url
resource = restkit.Resource(base_url)
path = '/repos/%s/%s/pulls/%s' % (org, repo, pr)
response = resource.get(path, headers={'Accept': 'application/json'})
json = json.loads(response.body_string())
branch_name = json['head']['label']

print "##teamcity[setParameter name='teamcity.build.branch' value='%s']" % branch_name

