#!/usr/bin/env python3

import sys

from idea_http import print_json, request_json


USAGE = """Usage: idea-changelist <command>
Commands:
  list
  create <name>
  set-default <name>
  delete <name>"""


def usage() -> None:
    print(USAGE, file=sys.stderr)
    raise SystemExit(1)


def main(argv: list[str]) -> int:
    if len(argv) < 2:
        usage()

    command = argv[1]

    try:
        if command == "list":
            print_json(request_json("GET", "/changelists"))
            return 0
        if command == "create" and len(argv) == 3:
            request_json("POST", "/changelists/create", {"name": argv[2]})
            print()
            return 0
        if command == "set-default" and len(argv) == 3:
            request_json("POST", "/changelists/set-default", {"name": argv[2]})
            print()
            return 0
        if command == "delete" and len(argv) == 3:
            request_json("POST", "/changelists/delete", {"name": argv[2]})
            print()
            return 0
    except RuntimeError as exc:
        print(exc, file=sys.stderr)
        return 1

    usage()
    return 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
