#!/bin/bash
 
xrandr

# screen width (the effective resolution! just set yours here.)
screen_width1=1920
screen_width2=1920

window_ids=$(wmctrl -l | awk '{print $1}')
echo "Window ids: $window_ids"

for window in $window_ids ; do
  x=$(xwininfo -id $window | grep "Absolute upper-left X" | awk '{print $4}')
  y=$(xwininfo -id $window | grep "Absolute upper-left Y" | awk '{print $4}')
  w=$(xwininfo -id $window | grep "Width" | awk '{print $2}')

  if [ "$x" -ge "$screen_width1" ]; then
    newx=$((x - 2 * screen_width1 + screen_width2))
    echo "Moving window $(wmctrl -l | grep $window) from $x,$y + $w to $newx,$y"

    maximized_vert=false
    if xprop -id $window _NET_WM_STATE | grep _NET_WM_STATE_MAXIMIZED_VERT ; then
        maximized_vert=true
        wmctrl -ir $window -b remove,maximized_vert
    fi

    maximized_horz=false
    if xprop -id $window _NET_WM_STATE | grep _NET_WM_STATE_MAXIMIZED_HORZ ; then
        maximized_horz=true
        wmctrl -ir $window -b remove,maximized_horz
    fi

    wmctrl -ir $window -e 0,$newx,$y,-1,-1
 
    if $maximized_vert; then
        wmctrl -ir $window -b add,maximized_vert
    fi
    if $maximized_horz; then
        wmctrl -ir $window -b add,maximized_horz
    fi
  fi
done
