#!/bin/sh

PR_BRANCH_PREFIX=pr_
TOPIC_BRANCH_PREFIX=$(git config sync.topicBranchPrefix)
#TOPIC_BRANCH_PREFIX=t_
RELEASE_BRANCHES=$(git config sync.releaseBranches)

function git_ls_branches() {
  git for-each-ref --format='%(refname:short)' "refs/heads/$1*" "refs/heads/$1*/*" "refs/heads/$1*/*/*" "refs/heads/$1*/*/*/*" "refs/heads/$1*/*/*/*/*" "refs/heads/$1*/*/*/*/*/*"
}

SAVED_BRANCH=$(git name-rev --name-only HEAD)

for tb in $(git_ls_branches $TOPIC_BRANCH_PREFIX) ; do
  rb=$(find_upstream_branch $tb)
  git rebase $rb $tb &>/dev/null || git rebase --abort
  if git merge-base --is-ancestor $tb $rb ; then
    echo Removing topic branch $tb merged in $rb
    git checkout -q $rb
    git branch --set-upstream-to=$rb $tb
    git branch -d $tb
    git push origin :$tb
    if [[ "$SAVED_BRANCH" == "$tb" ]]; then
      SAVED_BRANCH=$rb
    fi
  #else
  #  echo Ignoring branch $tb
  fi
done

for tb in $(git_ls_branches $PR_BRANCH_PREFIX) ; do
  rb=$(find_upstream_branch $tb)
  git rebase $rb $tb &>/dev/null || git rebase --abort
  if git merge-base --is-ancestor $tb $rb ; then
    echo Removing PR review branch $tb merged in $rb
    git checkout -q $rb
    git branch --set-upstream-to=$rb $tb
    git branch -d $tb
    if [[ "$SAVED_BRANCH" == "$tb" ]]; then
      SAVED_BRANCH=$rb
    fi
  #else
  #  echo Ignoring branch $tb
  fi
done


# for prb in $(git_ls_branches $PR_BRANCH_PREFIX) ; do git checkout -q $prb ; git rebase -q $(find_upstream_branch) &>/dev/null || git rebase --abort ; done
#git checkout -q master
git reset

git checkout -q $SAVED_BRANCH
echo Topic branches not integrated yet: $(git_ls_branches $TOPIC_BRANCH_PREFIX | tr -d '*')
echo PR branches not integrated yet: $(git_ls_branches $PR_BRANCH_PREFIX | tr -d '*')
echo Other branches: $(git_ls_branches | grep -v "^\($TOPIC_BRANCH_PREFIX\|$PR_BRANCH_PREFIX\)")
