#!/bin/sh

set -e

PR_BRANCH_PREFIX=pr_
UPSTREAM=$(git config sync.upstreamRepo || true)
TOPIC_BRANCH_PREFIX=$(git config sync.topicBranchPrefix || true)
#TOPIC_BRANCH_PREFIX=t_
RELEASE_BRANCHES=$(git config sync.releaseBranches || true)

function git_ls_branches() {
  git for-each-ref --format='%(refname:short)' "refs/heads/$1*" "refs/heads/$1*/*" "refs/heads/$1*/*/*" "refs/heads/$1*/*/*/*" "refs/heads/$1*/*/*/*/*" "refs/heads/$1*/*/*/*/*/*"
}

if [ -z "$TOPIC_BRANCH_PREFIX" ]; then
  echo "$0: config sync.topicBranchPrefix not set"
  exit 1
fi

if [ -z "$RELEASE_BRANCHES" ]; then
  echo "$0: config sync.releaseBranches not set"
  exit 1
fi


SAVED_BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [[ -n"$(git status --porcelain --untracked-files=no)" ]]; then
	git stash save "remove_integrated_topic_branches backup"
fi

for tb in $(git_ls_branches $TOPIC_BRANCH_PREFIX) ; do
  rb=$(find_upstream_branch $tb)
  # Checkout could fail because the branch is checked out in another worktree
  if git switch -q $tb ; then
    # The rebase could fail because it has conflicts
    git rebase $rb $tb &>/dev/null || git rebase --abort
    if git merge-base --is-ancestor $tb $rb ; then
      echo Removing topic branch $tb merged in $rb
      git checkout -q $rb
      git branch --set-upstream-to=$rb $tb
      git branch -d $tb
      git push origin :$tb || true
      if [[ "$SAVED_BRANCH" == "$tb" ]]; then
        SAVED_BRANCH=$rb
      fi
    fi
  fi
done

for tb in $(git_ls_branches $PR_BRANCH_PREFIX) ; do
  rb=$(find_upstream_branch $tb)
  # Checkout could fail because the branch is checked out in another worktree
  if git switch -q $tb ; then
    # The rebase could fail because it has conflicts
    git rebase $rb $tb &>/dev/null || git rebase --abort
    if git merge-base --is-ancestor $tb $rb ; then
      echo Removing PR review branch $tb merged in $rb
      git checkout -q $rb
      git branch --set-upstream-to=$UPSTREAM/$rb $tb
      git branch -d $tb
      if [[ "$SAVED_BRANCH" == "$tb" ]]; then
        SAVED_BRANCH=$rb
      fi
    fi
  fi
done


# for prb in $(git_ls_branches $PR_BRANCH_PREFIX) ; do git checkout -q $prb ; git rebase -q $(find_upstream_branch) &>/dev/null || git rebase --abort ; done
#git checkout -q master
git reset
git checkout -q $SAVED_BRANCH

if git stash list --format="%s" | grep -q "remove_integrated_topic_branches backup"; then
	git stash pop
fi


echo Topic branches not integrated yet:
echo $(git_ls_branches $TOPIC_BRANCH_PREFIX | tr -d '*')
echo
echo PR branches not integrated yet:
echo $(git_ls_branches $PR_BRANCH_PREFIX | tr -d '*')
echo
echo Other branches:
echo $(git_ls_branches | grep -v "^\($TOPIC_BRANCH_PREFIX\|$PR_BRANCH_PREFIX\)")
